- name: '`np-toorak`.`dw_bronze`.`bsi_loan`'
  columns:
    LOAN_NUMBER: STRING
    COLLATERAL_DESC: STRING
    FHA_VA_ACCT_NBR: INT64
    INVESTOR_CODE: STRING
    INVESTOR_BLOCK_CODE: STRING
    INVESTOR_POOL: STRING
    PRINCIPAL_BAL: STRING
    INTEREST_RT: STRING
    PI_PMT: STRING
    TI_PMT: STRING
    NEXT_PI_TI_PMT: STRING
    PMT_FREQUENCY: STRING
    INTEREST_PAID_TO_DATE: STRING
    NEXT_PAYMENT_DUE_DATE: STRING
    LAST_PMT_DATE: STRING
    DAYS_LATE: STRING
    PMT_METHOD: STRING
    ACH_STATUS: STRING
    YTD_INTEREST_PD: STRING
    YTD_INTEREST_ON_ESCROW: STRING
    YTD_TAXES_PD: STRING
    ESCROW_PMT_CHNG_DATE: STRING
    ESCROW_PMT_CHNG_AMT: STRING
    ESCROW_ANALYSIS_DATE: STRING
    ESCROW_PAY_INTEREST: STRING
    ESCROW_LAST_ANALYSIS_DATE: STRING
    ESCROW_BAL: STRING
    RESTRICTED_ESCROW_BAL: STRING
    TAX_CONTRACT_NUM: STRING
    FLOOD_CD: STRING
    FLOOD_MAP_DATE: STRING
    FLOOD_ZONE: STRING
    UNAP_BAL_1: STRING
    UNAP_CD_1: STRING
    UNAP_BAL_2: STRING
    UNAP_CD_2: STRING
    UNAP_BAL_3: STRING
    UNAP_CD_3: STRING
    UNAP_BAL_4: STRING
    UNAP_CD_4: STRING
    UNAP_BAL_5: STRING
    UNAP_CD_5: STRING
    UNAP_BAL_TOTAL: STRING
    BPO_1_VALUE: STRING
    BPO_1_VALUE_DATE: STRING
    ORIG_APPRAISAL_AMT: STRING
    ORIG_APPRAISAL_DATE: STRING
    CREDIT_RISK_SCORE_1: STRING
    CREDIT_RISK_SCORE_1_DATE: STRING
    REPORT_TO_CREDIT_BUREAU: STRING
    LATE_CHARGES_DUE: STRING
    LATE_CHARGE_CODE: STRING
    LATE_CHARGE_RATE: STRING
    LATE_CHARGE_GRACE_DAYS: STRING
    LATE_CHARGE_MIN: STRING
    LATE_CHARGE_MAX: STRING
    BORROWERS_NAME_PRIMARY: STRING
    BORROWERS_NAME_SECONDARY: STRING
    MAIL_LINE_1: STRING
    MAIL_LINE_2: STRING
    MAIL_CITY: STRING
    MAIL_STATE: STRING
    MAIL_ZIP: STRING
    HOME_PHN: STRING
    PROP_LINE_1: STRING
    PROP_LINE_2: STRING
    PROP_CITY: STRING
    PROP_STATE: STRING
    PROP_ZIP: STRING
    PROP_COUNTY: STRING
    COLLATERAL_CD: STRING
    STOP_CD_1: STRING
    STOP_CD_2: STRING
    STOP_CD_3: STRING
    LOCKOUT_CD: STRING
    WARNING_CD: STRING
    CLOSE_CD: STRING
    PROP_CONDITION_CD: STRING
    PROPERTY_TYPE_CD: STRING
    PREPAYMENT_PENALTY_CD: STRING
    LOAN_TYPE: STRING
    LOAN_SUBTYPE: STRING
    LIEN_POSITION: STRING
    OCCUPANCY_STATUS: STRING
    BK_FLAG: STRING
    LOSS_MIT_FLAG: STRING
    ARM_FLAG: STRING
    REASON_CLOSED: STRING
    TOTAL_LOAN_FEES: STRING
    MI_CERTIFICATE: STRING
    INSURER_CODE: STRING
    DELQ_DAYS_INCLUDING_GRACE_DAYS: STRING
    DLQ_STATUS: STRING
    CURRENT_LOAN_STATUS: STRING
    TERM_OF_LOAN: STRING
    PMT_CYC_TO_MATURITY: STRING
    DT_OF_LAST_TRAN: STRING
    MATURITY_DATE: STRING
    BALLOON_FLAG: STRING
    BALLOON_DATE: INT64
    ORIG_BAL: STRING
    NOTE_DATE: STRING
    OCCUPANCY_CD: STRING
    FIRST_PMT_DUE_DATE: STRING
    PAID_OFF_DATE: STRING
    CHARGE_OFF_DATE: STRING
    BOARDED_TO_LOANSERV_DATE: STRING
    SERVICE_TRANSFER_DATE: STRING
    PAYOFF_QUOTE_DATE: STRING
    DSI_LOAN: STRING
    LOAN_PURPOSE_CODE: STRING
    ORIGINAL_LTV_CALC: STRING
    IO_FLAG: STRING
    IO_TERM: STRING
    IO_END_DATE: STRING
    APPLICATION_TYPE: STRING
    INV_ACCT_NBR: STRING
    LAST_CONTACT_DATE: STRING
    LAST_ATTEMPT_DATE: STRING
    PROMISE_TO_PAY_DATE: STRING
    SKIP_TRACE_DATE: STRING
    NSF_LAST_DATE: STRING
    NSF_CK_COUNT: STRING
    FNMA_ACTION_CODE: STRING
    LAST_INSPECTION_DATE: STRING
    CURR_INDX_RATE: STRING
    MARGIN: STRING
    OPTION_ARM: INT64
    INTR_RECV_BAL: STRING
    LINE_FREEZE_EFF_DT: STRING
    LINE_DRAW_END_DT: STRING
    LINE_TOTAL_ADV_LIFE: STRING
    INVESTOR_NAME: STRING
    DATA_DATE: STRING
    InvestorNetInterestRate: STRING
    InvestorServiceFeeRate: STRING
    InterestMethod: STRING
    CurrRehabFundsBal: STRING
    OrigRehabFundsBal: STRING
    file_date: STRING
    ingestion_date: DATE
